MANIFEST: manifest.tab
DETECT_CALLERS: pbsv,sawfish,sniffles,delly,cutesv
MERGE_CALLERS: pav,pbsv,sawfish,sniffles,delly,cutesv
REF:
  CHM13: /net/eichler/vol28/eee_shared/assemblies/CHM13/T2T/v2.0/T2T-CHM13v2.fasta
  GRCh38: /net/eichler/vol28/eee_shared/assemblies/hg38/no_alt/hg38.no_alt.fa
TRMASK:
  CHM13: /net/eichler/vol28/projects/medical_reference/nobackups/ref_diff/chm13/chm13v2.0_maskedY_rCRS.platinumTRs-v1.0.trgt.annotations.bed.gz
  GRCh38: /net/eichler/vol28/projects/medical_reference/nobackups/ref_diff/hg38/human_GRCh38_no_alt_analysis_set.platinumTRs-v1.0.trgt.annotations.bed.gz
CPRMASK:
  CHM13: /net/eichler/vol28/projects/medical_reference/nobackups/ref_diff/chm13/chm13v2.0_complex_sat.bed
  GRCh38: /net/eichler/vol28/projects/medical_reference/nobackups/ref_diff/hg38/hg38_complexRegions.bed

